/** Derived views: JSON, JSONL, CSV and a SQL script for sqlite3. */

import type { Json } from "./jsonschema.ts";
import type { FileAnalysis } from "./lint.ts";


export type ExportFormat = "json" | "jsonl" | "csv" | "sqlite";

export interface ExportRow {
  _id: string;
  _type: string;
  _path: string;
  [key: string]: Json;
}

export interface ExportEdge {
  from_id: string;
  field: string;
  to_id: string;
}

export interface ExportData {
  rows: ExportRow[];
  /** Type name to the table name from `x-tmd.plural`. */
  plural: Map<string, string>;
  edges: ExportEdge[];
}

export interface ExportFile {
  /** Path relative to the output folder, or "-" for a single stream. */
  name: string;
  content: string;
}

export function collect(analyses: FileAnalysis[], withBody: boolean): ExportData {
  const rows: ExportRow[] = [];
  const plural = new Map<string, string>();
  const edges: ExportEdge[] = [];
  for (const analysis of analyses) {
    const file = analysis.file;
    if (file.id === null || file.type === null || analysis.schema === null || analysis.data === null) continue;
    plural.set(file.type, analysis.schema.plural);
    const row: ExportRow = { _id: file.id, _type: file.type, _path: file.rel, ...analysis.data };
    if (withBody) row["_body"] = (file.frontmatter?.body ?? "").trim();
    rows.push(row);
    for (const ref of analysis.refs) {
      if (ref.targetId === null) continue;
      edges.push({ from_id: file.id, field: ref.field, to_id: ref.targetId });
    }
  }
  rows.sort((a, b) => (a._id < b._id ? -1 : a._id > b._id ? 1 : 0));
  edges.sort((a, b) =>
    a.from_id === b.from_id ? (a.field < b.field ? -1 : 1) : a.from_id < b.from_id ? -1 : 1,
  );
  return { rows, plural, edges };
}

/** Nested objects become dot keys, arrays are joined with `;`. */
export function flatten(value: Json, prefix = ""): { [key: string]: string } {
  const out: { [key: string]: string } = {};
  if (value === null) {
    out[prefix] = "";
    return out;
  }
  if (Array.isArray(value)) {
    out[prefix] = value
      .map((item) => (item !== null && typeof item === "object" ? JSON.stringify(item) : String(item)))
      .join(";");
    return out;
  }
  if (typeof value === "object") {
    for (const [key, item] of Object.entries(value)) {
      const next = prefix === "" ? key : `${prefix}.${key}`;
      Object.assign(out, flatten(item!, next));
    }
    return out;
  }
  out[prefix] = String(value);
  return out;
}

export function csvCell(value: string): string {
  if (/[",\n\r]/.test(value)) return `"${value.replaceAll('"', '""')}"`;
  return value;
}

function orderedColumns(keys: Set<string>): string[] {
  const first = ["_id", "_type", "_path"];
  const rest = [...keys].filter((key) => !first.includes(key)).sort();
  return [...first.filter((key) => keys.has(key)), ...rest];
}

export function toCsv(rows: ExportRow[]): string {
  const flat = rows.map((row) => flatten(row as Json));
  const keys = new Set<string>();
  for (const row of flat) for (const key of Object.keys(row)) keys.add(key);
  const columns = orderedColumns(keys);
  const lines = [columns.map(csvCell).join(",")];
  for (const row of flat) lines.push(columns.map((column) => csvCell(row[column] ?? "")).join(","));
  return lines.join("\n") + "\n";
}

function sqlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlValue(value: Json | undefined): string {
  if (value === undefined || value === null) return "NULL";
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return value ? "1" : "0";
  if (typeof value === "object") return sqlString(JSON.stringify(value));
  return sqlString(value);
}

function sqlColumnType(rows: ExportRow[], column: string): string {
  let sawNumber = false;
  let allInteger = true;
  for (const row of rows) {
    const value = row[column];
    if (value === undefined || value === null) continue;
    if (typeof value === "number") {
      sawNumber = true;
      if (!Number.isInteger(value)) allInteger = false;
      continue;
    }
    if (typeof value === "boolean") continue;
    return "TEXT";
  }
  if (!sawNumber) return "TEXT";
  return allInteger ? "INTEGER" : "REAL";
}

/**
 * A SQL script, not a binary database. There is no zero dependency SQLite
 * writer, so `tmd export --format sqlite` writes a script you pipe into
 * sqlite3. See the README.
 */
export function toSql(data: ExportData): string {
  const byType = new Map<string, ExportRow[]>();
  for (const row of data.rows) {
    const bucket = byType.get(row._type);
    if (bucket) bucket.push(row);
    else byType.set(row._type, [row]);
  }
  const out: string[] = [
    "-- Generated by tmd export --format sqlite. Pipe it into sqlite3:",
    "--   tmd export --format sqlite --out brain.sql && sqlite3 brain.db < brain.sql",
    "PRAGMA foreign_keys = OFF;",
    "BEGIN TRANSACTION;",
  ];
  for (const [type, rows] of [...byType].sort((a, b) => (a[0] < b[0] ? -1 : 1))) {
    const table = data.plural.get(type) ?? `${type}s`;
    const keys = new Set<string>();
    for (const row of rows) for (const key of Object.keys(row)) keys.add(key);
    const columns = orderedColumns(keys);
    out.push("", `DROP TABLE IF EXISTS "${table}";`);
    const definitions = columns.map((column) => {
      const type = sqlColumnType(rows, column);
      return `  "${column}" ${type}${column === "_id" ? " PRIMARY KEY" : ""}`;
    });
    out.push(`CREATE TABLE "${table}" (\n${definitions.join(",\n")}\n);`);
    for (const row of rows) {
      const values = columns.map((column) => sqlValue(row[column]));
      out.push(`INSERT INTO "${table}" (${columns.map((c) => `"${c}"`).join(", ")}) VALUES (${values.join(", ")});`);
    }
  }
  out.push("", 'DROP TABLE IF EXISTS "refs";');
  out.push('CREATE TABLE "refs" (\n  "from_id" TEXT,\n  "field" TEXT,\n  "to_id" TEXT\n);');
  for (const edge of data.edges) {
    out.push(
      `INSERT INTO "refs" ("from_id", "field", "to_id") VALUES (${sqlString(edge.from_id)}, ${sqlString(edge.field)}, ${sqlString(edge.to_id)});`,
    );
  }
  out.push("", "COMMIT;", "");
  return out.join("\n");
}

/** Build the files an export writes. CSV gives one file per type. */
export function buildExport(data: ExportData, format: ExportFormat): ExportFile[] {
  switch (format) {
    case "json":
      return [{ name: "-", content: JSON.stringify(data.rows, null, 2) + "\n" }];
    case "jsonl":
      return [{ name: "-", content: data.rows.map((row) => JSON.stringify(row)).join("\n") + (data.rows.length > 0 ? "\n" : "") }];
    case "sqlite":
      return [{ name: "-", content: toSql(data) }];
    case "csv": {
      const byType = new Map<string, ExportRow[]>();
      for (const row of data.rows) {
        const bucket = byType.get(row._type);
        if (bucket) bucket.push(row);
        else byType.set(row._type, [row]);
      }
      return [...byType]
        .sort((a, b) => (a[0] < b[0] ? -1 : 1))
        .map(([type, rows]) => ({ name: `${data.plural.get(type) ?? `${type}s`}.csv`, content: toCsv(rows) }));
    }
  }
}

export function defaultOutName(format: ExportFormat): string {
  switch (format) {
    case "json":
      return "tmd-export.json";
    case "jsonl":
      return "tmd-export.jsonl";
    case "sqlite":
      return "tmd-export.sql";
    case "csv":
      return "tmd-export";
  }
}
